[general]
import = ["~/.config/alacritty/catppuccin-latte.toml"]

[env]
TERM = "xterm-256color"

[window]
dynamic_padding = true
decorations = "Transparent"
blur = true
opacity = 0.75

[scrolling]
history = 10000

[font]
normal = { family = "MesloLGS NF", style = "Regular" }
size = 12
offset = { x = 0, y = 2 }

[colors]
transparent_background_colors = true

[cursor]
style = { shape = "Block", blinking = "On" }
